language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t stefanbogdan180394/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true stefanbogdan180394/docker-test npm run test  